/**
 * scripts/bench-record.mjs — capture a saved run.
 *
 * Drives the real benchmark page in a real browser, waits for a full pass, and
 * writes the table to src/Bench/saved/<id>.json. Nothing here re-measures
 * anything: the numbers are lifted from the page that just displayed them, so a
 * saved run is exactly what a visitor with this machine would have seen.
 *
 *   node scripts/bench-record.mjs --label "M4 Max · Chrome 141"
 *
 * Saved runs are read-only in the UI. The page's whole purpose is comparison,
 * and a table half-measured here and half on someone's laptop compares nothing.
 */
import http from 'node:http';
import { existsSync, readFileSync, statSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, extname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { launch } from './browser.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = join(ROOT, 'dist');
const SAVED = join(ROOT, 'src/Bench/saved');

const argv = process.argv.slice(2);
const arg = n => { const i = argv.indexOf(n); return i >= 0 ? argv[i + 1] : null; };
const label = arg('--label') || 'unlabelled run';
const stamp = arg('--date') || new Date().toISOString().slice(0, 10);
const id = arg('--id') || `${stamp}-${label.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}`;

if (!existsSync(join(DIST, 'benchmark', 'index.html')) && !existsSync(join(DIST, 'benchmark.html'))) {
  console.error('bench-record: build first — dist/benchmark is missing');
  process.exit(1);
}

const TYPES = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.json': 'application/json', '.png': 'image/png', '.gif': 'image/gif', '.svg': 'image/svg+xml' };
const srv = http.createServer((q, r) => {
  const u = decodeURIComponent(q.url.split('?')[0]);
  for (const p of [join(DIST, u), join(DIST, `${u}.html`), join(DIST, u, 'index.html')]) {
    if (existsSync(p) && statSync(p).isFile()) {
      r.writeHead(200, { 'content-type': TYPES[extname(p)] || 'application/octet-stream' });
      return r.end(readFileSync(p));
    }
  }
  r.writeHead(404);
  return r.end('not found');
});
await new Promise(r => srv.listen(0, r));
const base = `http://localhost:${srv.address().port}`;

const browser = await launch();
const page = await browser.newPage();
page.on('pageerror', e => console.log('  page error:', String(e.message).slice(0, 120)));
await page.setViewport({ width: 1400, height: 1000 });
await page.goto(`${base}/benchmark`, { waitUntil: 'networkidle2' });
await new Promise(r => setTimeout(r, 1200));

const rows = await page.evaluate(() => document.querySelectorAll('#root tbody tr').length);
console.log(`bench-record: ${rows} workload(s), running…`);
await page.click('.toolbar .btn.primary');

let done = false;
for (let i = 0; i < 400 && !done; i++) {
  // eslint-disable-next-line no-await-in-loop
  await new Promise(r => setTimeout(r, 3000));
  // eslint-disable-next-line no-await-in-loop
  const s = await page.evaluate(() => window.__benchStatus || '');
  if (/^done|^stopped/.test(s)) done = true;
  else if (i % 5 === 0) console.log(`  ${s}`);
}
if (!done) {
  console.error('bench-record: timed out; nothing written');
  process.exit(1);
}

const results = await page.evaluate(() => window.__benchResults);
const ua = await page.evaluate(() => navigator.userAgent);
const adapter = await page.evaluate(async () => {
  try {
    const a = await navigator.gpu.requestAdapter();
    const info = a && (a.info || (a.requestAdapterInfo ? await a.requestAdapterInfo() : null));
    return info ? [info.vendor, info.architecture, info.description].filter(Boolean).join(' ') : 'unknown adapter';
  } catch (e) { return 'no adapter'; }
});
await browser.close();
srv.close();

const chrome = (ua.match(/Chrome\/(\d+)/) || [])[1];
const run = {
  id,
  label,
  machine: `${adapter}${chrome ? ` · Chrome ${chrome}` : ''}`,
  date: stamp,
  gpujs: JSON.parse(readFileSync(join(ROOT, 'node_modules/gpu.js/package.json'), 'utf8')).version,
  results,
};
writeFileSync(join(SAVED, `${id}.json`), `${JSON.stringify(run, null, 2)}\n`);

// regenerate the index from whatever is on disk, newest first
const files = readdirSync(SAVED).filter(f => f.endsWith('.json')).sort().reverse();
writeFileSync(join(SAVED, 'index.js'),
`/**
 * src/Bench/saved/index.js — GENERATED by scripts/bench-record.mjs.
 *
 * A saved run is a whole table captured on one machine at one moment. The page
 * exists to compare backends, and a table half-measured here and half on
 * someone else's laptop compares nothing — so saved runs are read-only in the
 * UI and the picker chooses WHICH machine you are reading.
 *
 * Never hand-edited: a number in this directory has to have been measured.
 */
${files.map((f, i) => `import r${i} from './${f}';`).join('\n')}

export default [${files.map((_, i) => `r${i}`).join(', ')}];
`);
console.log(`bench-record: wrote ${id}.json (${Object.keys(results).length} rows) and rebuilt the index`);
