// GENERATED by scripts/capture-module-renders.mjs — do not edit by hand.
//
// Slugs whose module paints something worth showing, and therefore have a
// captured render at /img/modules/<slug>.png. Everything else falls back to
// the module's first figure. Rebuild with `--manifest` (no browser needed).
export default new Set([
  "cellular-automata",
  "colour-spaces",
  "convolution-and-filters",
  "escape-time-fractals",
  "hydraulic-erosion",
  "ising-model",
  "jump-flooding",
  "optical-flow",
  "path-tracing",
  "pixels-from-scratch",
  "ray-marched-metaballs",
  "reaction-diffusion",
  "seam-carving",
  "sequence-alignment",
  "spectrograms",
  "video-filters"
]);
