// GENERATED by scripts/capture-module-renders.mjs — do not edit by hand.
//
// Slug -> content hash of its captured render, for the modules that paint
// something worth showing. Everything else falls back to the module first
// figure. Rebuild with `--manifest` (no browser needed).
//
// The hash is the CACHE KEY, and it is why this is a Map and not a Set.
// /img/modules/<slug>.png is a stable URL whose BYTES change whenever the
// art is re-captured — unlike the Vite bundle, whose filename changes with
// its contents. Cloudflare and the browser both cache it for four hours,
// and the deploy purges HTML only (assets are meant to be immutable), so
// new art silently kept serving the old picture. Worse, a purge cannot
// reach a phone's own cache. Hanging the hash off the URL as ?v= makes new
// art a new URL, which is fetched immediately and cached just as long.
export default new Map([
  [
    "cellular-automata",
    "0cf06993"
  ],
  [
    "colour-spaces",
    "09f8706a"
  ],
  [
    "escape-time-fractals",
    "d9e7837d"
  ],
  [
    "hydraulic-erosion",
    "96ec4357"
  ],
  [
    "ising-model",
    "8a5b98b1"
  ],
  [
    "jump-flooding",
    "48b58875"
  ],
  [
    "optical-flow",
    "ee04cb3f"
  ],
  [
    "path-tracing",
    "7d17a829"
  ],
  [
    "pixels-from-scratch",
    "ec2fb488"
  ],
  [
    "ray-marched-metaballs",
    "2070daac"
  ],
  [
    "reaction-diffusion",
    "30e35e8d"
  ],
  [
    "seam-carving",
    "9f3bf443"
  ],
  [
    "sequence-alignment",
    "fe49ba13"
  ],
  [
    "spectrograms",
    "6b34e10f"
  ],
  [
    "video-filters",
    "81fdac12"
  ]
]);
