// GENERATED by scripts/capture-module-gifs.mjs — do not edit by hand.
//
// Slug -> content hash of its animated card, for the modules whose payoff
// has a dial worth turning. The catalogue shows the still by default and
// swaps to this on hover; see ModuleThumb for why it is not simply always
// animated.
export default new Map([
  [
    "cellular-automata",
    "ad5a503b"
  ],
  [
    "escape-time-fractals",
    "3fc59433"
  ],
  [
    "hydraulic-erosion",
    "e2d2ac56"
  ],
  [
    "ising-model",
    "f514fd9c"
  ],
  [
    "seam-carving",
    "feef14d9"
  ],
  [
    "sequence-alignment",
    "0948d1d4"
  ]
]);
