// GENERATED by scripts/capture-module-gifs.mjs — do not edit by hand.
//
// Slug -> content hash of its animated card, for the modules whose payoff
// has a dial worth turning. The catalogue shows the still by default and
// swaps to this on hover; see ModuleThumb for why it is not simply always
// animated.
export default new Map([
  [
    "cellular-automata",
    "ad5a503b"
  ],
  [
    "escape-time-fractals",
    "3fc59433"
  ],
  [
    "hydraulic-erosion",
    "e2d2ac56"
  ],
  [
    "ising-model",
    "f514fd9c"
  ],
  [
    "path-tracing",
    "cc162c43"
  ],
  [
    "pixels-from-scratch",
    "3f7a20d0"
  ],
  [
    "ray-marched-metaballs",
    "5e32a627"
  ],
  [
    "reaction-diffusion",
    "7aacaa61"
  ],
  [
    "seam-carving",
    "feef14d9"
  ],
  [
    "sequence-alignment",
    "0948d1d4"
  ],
  [
    "spectrograms",
    "4a89287e"
  ],
  [
    "video-filters",
    "f63f99aa"
  ]
]);
