// GENERATED by scripts/capture-module-renders.mjs — do not edit by hand.
//
// Slugs whose module paints something, and therefore has a real captured
// render at /img/modules/<slug>.png. Everything else falls back to the
// module's first figure. Regenerate with `node scripts/capture-module-renders.mjs`.
export default new Set([
  "cellular-automata",
  "colour-spaces",
  "convolution-and-filters",
  "data-in-data-out",
  "escape-time-fractals",
  "hydraulic-erosion",
  "ising-model",
  "jump-flooding",
  "optical-flow",
  "path-tracing",
  "pipelines-and-textures",
  "pixels-from-scratch",
  "ray-marched-metaballs",
  "reaction-diffusion",
  "seam-carving",
  "sequence-alignment",
  "spectrograms",
  "video-filters"
]);
